# Generated by Django 6.0.3 on 2026-03-31 09:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField()),
                ('city', models.CharField(choices=[('karachi', 'Karachi'), ('lahore', 'Lahore'), ('islamabad', 'Islamabad'), ('rawalpindi', 'Rawalpindi'), ('faisalabad', 'Faisalabad'), ('multan', 'Multan'), ('peshawar', 'Peshawar'), ('quetta', 'Quetta'), ('sialkot', 'Sialkot'), ('gujranwala', 'Gujranwala'), ('hyderabad', 'Hyderabad'), ('bahawalpur', 'Bahawalpur'), ('sargodha', 'Sargodha'), ('sukkur', 'Sukkur'), ('larkana', 'Larkana'), ('sahiwal', 'Sahiwal'), ('gujrat', 'Gujrat'), ('sheikhupura', 'Sheikhupura'), ('jhang', 'Jhang'), ('rahim_yar_khan', 'Rahim Yar Khan'), ('abbottabad', 'Abbottabad'), ('mardan', 'Mardan'), ('mingora', 'Mingora'), ('dera_ghazi', 'Dera Ghazi Khan'), ('nawabshah', 'Nawabshah'), ('mirpur', 'Mirpur (AJK)'), ('muzaffarabad', 'Muzaffarabad'), ('other', 'Other')], max_length=100)),
                ('province', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=200, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_method', models.CharField(choices=[('cod', 'Cash on Delivery'), ('jazzcash', 'JazzCash'), ('easypaisa', 'EasyPaisa')], default='cod', max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('pending', '⏳ Pending'), ('confirmed', '✅ Confirmed'), ('packed', '📦 Packed'), ('shipped', '🚚 Shipped'), ('delivered', '🎉 Delivered'), ('cancelled', '❌ Cancelled'), ('returned', '↩️ Returned')], default='pending', max_length=20)),
                ('tracking_code', models.CharField(blank=True, max_length=100)),
                ('whatsapp_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('note', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='orders.order')),
            ],
        ),
    ]
